name: Android CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Run espresso tests
      uses: ReactiveCircus/android-emulator-runner@v2.23.0
      with:
        api-level: 29
        arch: x86_64
        profile: Nexus 6
        target: default
        run: ./gradlew connectedDebugAndroidTest
